"""Add borrado field to LugarNoticia

Revision ID: 0e707b8f98d5
Revises: b2c3d4e5f6a7
Create Date: 2026-01-21 07:31:01.739281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e707b8f98d5'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos_referencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_referencias_articulo'))
        batch_op.drop_index(batch_op.f('idx_referencias_noticia'))

    op.drop_table('articulos_referencias')
    op.drop_table('articulos_figuras')
    with op.batch_alter_table('articulos_cientificos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_articulos_estado'))
        batch_op.drop_index(batch_op.f('idx_articulos_proyecto'))
        batch_op.drop_index(batch_op.f('idx_articulos_user'))

    op.drop_table('articulos_cientificos')
    with op.batch_alter_table('articulos_versiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_versiones_articulo'))

    op.drop_table('articulos_versiones')
    op.drop_table('plantillas_secciones')
    with op.batch_alter_table('geo_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_geo_places_lookup'))
        batch_op.drop_index(batch_op.f('idx_geo_places_status'))
        batch_op.drop_constraint(batch_op.f('geo_places_proyecto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'])

    with op.batch_alter_table('hemerotecas', schema=None) as batch_op:
        batch_op.create_index('idx_hemeroteca_nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_hemeroteca_proyecto_id', ['proyecto_id'], unique=False)

    with op.batch_alter_table('lugar_noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrado', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_lugar_noticia_noticia_id'))

    with op.batch_alter_table('prensa', schema=None) as batch_op:
        batch_op.alter_column('id_publicacion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('anio',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('numero_referencia',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número secuencial para referencias bibliográficas (ej: [1], [2], [3]). Solo aplicable cuando incluido = true',
               existing_nullable=True)
        batch_op.alter_column('edicion',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('creado_en',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('modificado_en',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_prensa_incluido_numero'), postgresql_where='((incluido = true) AND (numero_referencia IS NOT NULL))')
        batch_op.drop_index(batch_op.f('idx_prensa_numero_referencia'), postgresql_where='(numero_referencia IS NOT NULL)')
        batch_op.create_index('idx_prensa_anio', ['anio'], unique=False)
        batch_op.create_index('idx_prensa_autor', ['nombre_autor'], unique=False)
        batch_op.create_index('idx_prensa_ciudad', ['ciudad'], unique=False)
        batch_op.create_index('idx_prensa_fecha_original', ['fecha_original'], unique=False)
        batch_op.create_index('idx_prensa_id_publicacion', ['id_publicacion'], unique=False)
        batch_op.create_index('idx_prensa_incluido', ['incluido'], unique=False)
        batch_op.create_index('idx_prensa_publicacion', ['publicacion'], unique=False)
        batch_op.drop_constraint(batch_op.f('prensa_proyecto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'])
        batch_op.create_foreign_key(None, 'publicaciones', ['id_publicacion'], ['id_publicacion'])
        batch_op.drop_column('status_derechos')

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index('idx_proyecto_nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_proyecto_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_publicaciones_proyecto_id'))
        batch_op.create_index('idx_publicacion_hemeroteca_id', ['hemeroteca_id'], unique=False)
        batch_op.create_index('idx_publicacion_nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_publicacion_proyecto_id', ['proyecto_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('publicaciones_proyecto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('publicaciones_hemeroteca_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hemerotecas', ['hemeroteca_id'], ['id'])
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'])
        batch_op.drop_column('descripcion_publicacion')
        batch_op.drop_column('pais')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('usuarios_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_username_key'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'])
        pass
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descripcion_publicacion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publicaciones_hemeroteca_id_fkey'), 'hemerotecas', ['hemeroteca_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('publicaciones_proyecto_id_fkey'), 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('idx_publicacion_proyecto_id')
        batch_op.drop_index('idx_publicacion_nombre')
        batch_op.drop_index('idx_publicacion_hemeroteca_id')
        batch_op.create_index(batch_op.f('idx_publicaciones_proyecto_id'), ['proyecto_id'], unique=False)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index('idx_proyecto_user_id')
        batch_op.drop_index('idx_proyecto_nombre')

    with op.batch_alter_table('prensa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_derechos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prensa_proyecto_id_fkey'), 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('idx_prensa_publicacion')
        batch_op.drop_index('idx_prensa_incluido')
        batch_op.drop_index('idx_prensa_id_publicacion')
        batch_op.drop_index('idx_prensa_fecha_original')
        batch_op.drop_index('idx_prensa_ciudad')
        batch_op.drop_index('idx_prensa_autor')
        batch_op.drop_index('idx_prensa_anio')
        batch_op.create_index(batch_op.f('idx_prensa_numero_referencia'), ['numero_referencia'], unique=False, postgresql_where='(numero_referencia IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_prensa_incluido_numero'), ['incluido', 'numero_referencia'], unique=False, postgresql_where='((incluido = true) AND (numero_referencia IS NOT NULL))')
        batch_op.alter_column('modificado_en',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('edicion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('numero_referencia',
               existing_type=sa.INTEGER(),
               comment='Número secuencial para referencias bibliográficas (ej: [1], [2], [3]). Solo aplicable cuando incluido = true',
               existing_nullable=True)
        batch_op.alter_column('licencia',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('anio',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id_publicacion',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('lugar_noticia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lugar_noticia_noticia_id'), ['noticia_id'], unique=False)
        batch_op.drop_column('borrado')

    with op.batch_alter_table('hemerotecas', schema=None) as batch_op:
        batch_op.drop_index('idx_hemeroteca_proyecto_id')
        batch_op.drop_index('idx_hemeroteca_nombre')

    with op.batch_alter_table('geo_places', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('geo_places_proyecto_id_fkey'), 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_geo_places_status'), ['proyecto_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_geo_places_lookup'), ['proyecto_id', 'place_norm', 'pais'], unique=False)

    op.create_table('plantillas_secciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo_articulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secciones_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plantillas_secciones_pkey'))
    )
    op.create_table('articulos_versiones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido_snapshot', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cambios_descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_cientificos.id'], name=op.f('articulos_versiones_articulo_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('articulos_versiones_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('articulos_versiones_pkey'))
    )
    with op.batch_alter_table('articulos_versiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_versiones_articulo'), ['articulo_id'], unique=False)

    op.create_table('articulos_cientificos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subtitulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autores', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instituciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('resumen_es', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('abstract_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('palabras_clave', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contenido_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.TEXT(), server_default=sa.text("'borrador'::text"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('palabras_totales', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('paginas_estimadas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('plantilla', sa.TEXT(), server_default=sa.text("'janus'::text"), autoincrement=False, nullable=True),
    sa.Column('estilo_citas', sa.TEXT(), server_default=sa.text("'chicago'::text"), autoincrement=False, nullable=True),
    sa.Column('idioma_principal', sa.TEXT(), server_default=sa.text("'es'::text"), autoincrement=False, nullable=True),
    sa.Column('logo_institucional', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imagen_portada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version_anterior_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('historial_cambios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coautores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comentarios_revision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ultimo_autoguardado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_publicacion', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('articulos_cientificos_proyecto_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('articulos_cientificos_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_anterior_id'], ['articulos_cientificos.id'], name=op.f('articulos_cientificos_version_anterior_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('articulos_cientificos_pkey'))
    )
    with op.batch_alter_table('articulos_cientificos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_articulos_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_articulos_proyecto'), ['proyecto_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_articulos_estado'), ['estado'], unique=False)

    op.create_table('articulos_figuras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('archivo_ruta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seccion_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creditos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_cientificos.id'], name=op.f('articulos_figuras_articulo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('articulos_figuras_pkey'))
    )
    op.create_table('articulos_referencias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('noticia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seccion_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('orden_aparicion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pagina_numero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cita_textual', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nota_uso', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_cientificos.id'], name=op.f('articulos_referencias_articulo_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['noticia_id'], ['prensa.id'], name=op.f('articulos_referencias_noticia_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('articulos_referencias_pkey')),
    sa.UniqueConstraint('articulo_id', 'noticia_id', 'seccion_id', name=op.f('articulos_referencias_articulo_id_noticia_id_seccion_id_key'))
    )
    with op.batch_alter_table('articulos_referencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_referencias_noticia'), ['noticia_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_referencias_articulo'), ['articulo_id'], unique=False)

    # ### end Alembic commands ###
